name: CI

on: [push]

jobs:
  dkr_linux:
    runs-on: ubuntu-latest
    steps:
    - name: docker
      run: |
        docker run hello-world
  dkr_windows:
    runs-on: windows-latest
    steps:
    - name: docker
      run: |
        docker run hello-world
  dkr_macos:
    runs-on: macos-latest
    steps:
    - name: docker
      run: |
        docker run hello-world