name: CI

on: [push]

jobs:
  dkr_linux:
    runs-on: ubuntu-latest
    steps:
    - name: docker
      run: |
        docker run hello-world
  # dkr_windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 2
  #   - name: docker
  #     run: |
  #       docker info
  #       # docker build -t test/windows .
  #       # docker run test/windows cmd.exe /s /c echo "ok windows"
  #       & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchDaemon
  #       docker info
  #       .\dockercli.exe -SwitchLinuxEngine
  #       docker run alpine apk --version
  # dkr_macos:
  #   runs-on: macos-latest
  #   steps:
  #   - name: docker
  #     run: |
  #       brew install podman
  #       podman machine init
  #       podman machine start
  #       podman info
  #       podman run docker.io/library/hello-world
  dkr_macos:
    runs-on: macos-latest
    steps:
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        set -x
        docker version
        docker run --rm hello-world