name: CI

on: [push]

jobs:
  dkr_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
    - name: docker
      run: |
        pip install docker
        python main.py
  dkr_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
      - name: docker
        run: |
          pip install docker
          python main.py
  dkr_macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.5
    - name: docker
      run: |
          brew install docker colima
          colima start
          export DOCKER_HOST="unix://${HOME}/.colima/default/docker.sock"
          pip install docker
          python main.py
